import React from "react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

const services = [
  {
    num: "01",
    title: "Deal Flow Intelligence",
    pain: "Analysts spending 90 min/day copying pitch decks into your CRM.",
    outcomes: [
      "100% of deals logged automatically",
      "AI fit scoring on every inbound",
      "Slack alerts to the right partner instantly",
    ],
    build: "2–3 weeks",
  },
  {
    num: "02",
    title: "LP Report Generation",
    pain: "3–5 days every quarter building and sending LP reports by hand",
    outcomes: [
      "Full cycle automated end-to-end",
      "Personalized per LP commitment",
      "Narrative commentary generated by AI",
    ],
    build: "3–5 weeks",
  },
  {
    num: "03",
    title: "Portfolio KPI Monitoring",
    pain: "2–3 days/month chasing portcos for data and consolidating spreadsheets",
    outcomes: [
      "Automated data collection from all portcos",
      "AI anomaly detection on burn, revenue, covenants",
      "Real-time dashboard with alerts",
    ],
    build: "2–3 weeks",
  },
  {
    num: "04",
    title: "Due Diligence Automation",
    pain: "Associates reading 400-doc data rooms for days before IC",
    outcomes: [
      "Full data room processed in under an hour",
      "Structured memo with risks and flags extracted",
      "Human review only on flagged items",
    ],
    build: "3–5 weeks",
  },
  {
    num: "05",
    title: "Compliance & Filing Automation",
    pain: "Regulatory deadlines tracked in spreadsheets, missed = fines",
    outcomes: [
      "Automated reminders 30/14/7/1 days out",
      "Pre-filled draft filings generated",
      "Zero missed deadlines",
    ],
    build: "1–2 weeks",
  },
  {
    num: "06",
    title: "Fund Operations",
    pain: "Manual PDF notices, same DDQ questions answered from scratch, invoice coding by hand",
    outcomes: [
      "Capital call notices generated and sent per LP automatically",
      "DDQ knowledge base answers 80% of questions instantly",
      "Invoice GL coding and approval routing automated",
    ],
    build: "3–6 weeks",
  },
];

export default function Services() {
  return (
    <div style={{ fontFamily: "'DM Sans', sans-serif" }}>
      {/* Header */}
      <section className="bg-black pt-28 md:pt-36 pb-20 md:pb-28">
        <div className="max-w-7xl mx-auto px-6 md:px-10">
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
            className="text-[11px] tracking-[0.15em] uppercase mb-5"
            style={{ color: "#666666" }}
          >
            Workflows
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-[38px] md:text-[52px] leading-[1.15] text-white max-w-[700px] mb-6"
            style={{ fontFamily: "'Playfair Display', serif" }}
          >
            Proven workflows. Fixed price. Delivered in weeks.
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="text-[16px] md:text-[18px] leading-[1.7] max-w-[600px]"
            style={{ color: "#999999" }}
          >
            We specialize exclusively in private equity and venture capital operations. These are the workflows we know cold.
          </motion.p>
        </div>
      </section>

      {/* Services Grid */}
      <section className="bg-white py-20 md:py-28">
        <div className="max-w-7xl mx-auto px-6 md:px-10 grid grid-cols-1 md:grid-cols-2 gap-0">
          {services.map((svc, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.05 }}
              className="border border-[#E0E0E0] p-8 md:p-10 -mt-px -ml-px group hover:bg-[#FAFAFA] transition-colors duration-200 flex flex-col"
            >
              <span className="text-[56px] leading-none block mb-6" style={{ fontFamily: "'Playfair Display', serif", color: "#E0E0E0" }}>
                {svc.num}
              </span>
              <h3 className="text-[20px] font-bold text-black mb-3">{svc.title}</h3>
              <p className="text-[15px] italic mb-6" style={{ color: "#777777" }}>{svc.pain}</p>
              <ul className="space-y-2 mb-8 flex-1">
                {svc.outcomes.map((o, j) => (
                  <li key={j} className="text-[14px] text-black flex items-start gap-2">
                    <span className="mt-0.5 shrink-0">→</span>
                    <span>{o}</span>
                  </li>
                ))}
              </ul>
              <div className="flex items-center justify-between border-t border-[#E0E0E0] pt-5">
                <span className="text-[11px] tracking-[0.1em] uppercase" style={{ color: "#888" }}>{svc.build}</span>
                <Link
                  to={createPageUrl("Contact")}
                  className="text-[13px] text-black hover:underline"
                >
                  Book a call →
                </Link>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="bg-black py-24 md:py-32">
        <div className="max-w-[600px] mx-auto text-center px-6">
          <h2
            className="text-[30px] md:text-[38px] leading-[1.25] text-white mb-6"
            style={{ fontFamily: "'Playfair Display', serif" }}
          >
            Not sure which workflow to start with? That's what the audit is for.
          </h2>
          <Link
            to={createPageUrl("Contact")}
            className="inline-block border border-white text-white text-[14px] tracking-[0.05em] px-8 py-4 hover:bg-white hover:text-black transition-all duration-300"
          >
            Book Free Workflow Audit →
          </Link>
        </div>
      </section>
    </div>
  );
}